### ISSUE TITLE
Error saving VPN configuration

### ISSUE THREAD

**Issue by Jenil1501** [jurajhilje/DOHIKEv2Demo#1]
Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements.

**Comment by paulocoutinhox** [comment]
1 - Change the bundle ID to a new bundle ID, example "com.myvpn.app"
2 - Add keychain access on capabilities (it don't come selected)
3 - Then add you app bundle id "com.myvpn.app" to keychain groups in capabilities (signing and capabilities)
4 - Then change in KeyChain.swift the data on constructor, example `Keychain(service: "com.myvpn.app", accessGroup: "YOUR-TEAM-ID.com.myvpn.app")`

**Comment by Jenil1501** [comment]
Thank you so much.
